-- Notely: initial schema (generated by an AI coding tool, reviewed by nobody)
create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id),
  email text not null,
  full_name text,
  plan text not null default 'free',
  stripe_customer_id text
);
-- TODO: turn on RLS before launch

create table public.notes (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id),
  body text not null,
  created_at timestamptz not null default now()
);
alter table public.notes enable row level security;
create policy "notes are readable" on public.notes for select using (true);
create policy "users can update notes" on public.notes for update using (auth.uid() = user_id);

create view public.profile_directory as
  select id, full_name, email, plan from public.profiles;
